In [52]:
from numpy import linalg as LA
import numpy as np
from numpy import diagonal
import sys
import hashlib
sys.set_int_max_str_digits(999999)

In [10]:
def mmul(array_first,array_second):
    """This is the standard matrix multiplication O(n^3)"""
    n = len(array_first)
    result = np.zeros((n,n), dtype=object).tolist()

    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += array_first[i][k] *array_second[k][j]
    return result

In [267]:
p = 55692
q = -9549
r = 301
s = 21
a = np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[p,q,r,s]], dtype=np.int64)
eigenvectors = LA.eig(a).eigenvectors
# eigenvectors = np.array([[-1/9261, 1/1728, 1/2197, 1/4913], [1/441, 1/144, 1/169, 1/289], [-1/21, 1/12, 1/13, 1/17], [1,1,1,1]])
eigenvalues = np.diag(LA.eig(a).eigenvalues)
np.matmul(np.matmul((eigenvectors), eigenvalues, dtype=np.float64), LA.inv((eigenvectors)), dtype=np.float64)


array([[-6.13441159e-14,  1.00000000e+00,  1.35775706e-16,
        -1.68069501e-17],
       [-1.94126990e-12, -1.69996192e-14,  1.00000000e+00,
        -3.59603493e-16],
       [-1.64752292e-11,  2.02193258e-12,  7.39144724e-14,
         1.00000000e+00],
       [ 5.56920000e+04, -9.54900000e+03,  3.01000000e+02,
         2.10000000e+01]])

In [262]:
eigenvectors.round(3)

array([[-0.   ,  0.   ,  0.   ,  0.001],
       [ 0.002,  0.003,  0.006,  0.007],
       [-0.048,  0.059,  0.077,  0.083],
       [ 0.999,  0.998,  0.997,  0.997]])

In [263]:
np.array([[-1/9261, 1/1728, 1/2197, 1/4913], [1/441, 1/144, 1/169, 1/289], [-1/21, 1/12, 1/13, 1/17], [1,1,1,1]]).round(3)

array([[-0.   ,  0.001,  0.   ,  0.   ],
       [ 0.002,  0.007,  0.006,  0.003],
       [-0.048,  0.083,  0.077,  0.059],
       [ 1.   ,  1.   ,  1.   ,  1.   ]])

In [248]:
np.array([[-1/9261, 1/441, -1/21, 1], [1/1728, 1/144, 1/12, 1], [1/2197, 1/169, 1/13, 1], [1/4913, 1/289, 1/17, 1]])

array([[-1.07979700e-04,  2.26757370e-03, -4.76190476e-02,
         1.00000000e+00],
       [ 5.78703704e-04,  6.94444444e-03,  8.33333333e-02,
         1.00000000e+00],
       [ 4.55166136e-04,  5.91715976e-03,  7.69230769e-02,
         1.00000000e+00],
       [ 2.03541624e-04,  3.46020761e-03,  5.88235294e-02,
         1.00000000e+00]])

In [243]:
eigenvectors

array([[-1.07857204e-04,  2.03189171e-04,  4.53817493e-04,
         5.76690816e-04],
       [ 2.26500129e-03,  3.45421591e-03,  5.89962740e-03,
         6.92028979e-03],
       [-4.75650271e-02,  5.87216704e-02,  7.66951562e-02,
         8.30434775e-02],
       [ 9.98865570e-01,  9.98268397e-01,  9.97037031e-01,
         9.96521730e-01]])

In [221]:
np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[p,q,r,s]], dtype=np.int64)

array([[    0,     1,     0,     0],
       [    0,     0,     1,     0],
       [    0,     0,     0,     1],
       [55692, -9549,   301,    21]])

In [219]:
np.matmul(np.matmul((eigenvectors*100000000000000000000), eigenvalues), LA.inv((eigenvectors*100000000000000000000)))[0][0]*100000000000000000000000000000

np.float64(-5524718771513983.0)

In [85]:
from sympy import factorint
factorint(20000000)

{2: 8, 5: 7}

In [126]:
from tqdm import tqdm
a = np.matmul(np.matmul(eigenvectors.real, eigenvalues.real), LA.inv(eigenvectors.real)).astype(object).tolist()
temp = a
# int ervention
for k in tqdm(range(2000000)):
    temp = mmul(temp, a)
    if (k>=2**7):
        for i in range(len(temp)):
            for j in range(len(temp[0])):
                temp[i][j] = int(temp[i][j])
    if (k%100000)==0 and k!=0:
        for i in range(len(temp)):
            for j in range(len(temp[0])):
                temp[i][j] = int(temp[i][j])
        for i in range(len(temp)):
            for j in range(len(temp[0])):
                print(type(temp[i][j]))
                temp[i][j] = temp[i][j]%(10**10000)
    

  0%|          | 230/2000000 [00:00<00:36, 54983.75it/s]


OverflowError: cannot convert float infinity to integer

In [99]:
from tqdm import tqdm
a = np.matmul(np.matmul(eigenvectors.real, eigenvalues.real), LA.inv(eigenvectors.real)).astype(object).tolist()
temp = a
for i in range(7):
    temp = mmul(temp, temp)
# int ervention
for i in range(len(temp)):
    for j in range(len(temp[0])):
        temp[i][j] = int(temp[i][j])
print(temp[0][0])
for i in range(1):
    temp = mmul(temp, temp)

for i in tqdm(range(4)): # 
    temp = mmul(mmul(mmul(mmul(temp, temp), temp), temp), temp)

# fac tual answer
for i in range(len(temp)):
    for j in range(len(temp[0])):
        temp[i][j] = temp[i][j]%(10**10000)

for i in tqdm(range(2)): # 
    temp = mmul(mmul(mmul(mmul(temp, temp), temp), temp), temp)

# fac tual answer
for i in range(len(temp)):
    for j in range(len(temp[0])):
        temp[i][j] = temp[i][j]%(10**20000)

for i in tqdm(range(1)): # 
    temp = mmul(mmul(mmul(mmul(temp, temp), temp), temp), temp)

# # fac tual answer
# for i in range(len(temp)):
#     for j in range(len(temp[0])):
#         temp[i][j] = temp[i][j]%(10**10000)

1091105618678435497183229530068409710789954242322008814964771555466241421359557699814789902470354274878839008757997274222350625589638067812152264366893389134980718788608


100%|██████████| 1/1 [00:00<00:00,  1.71it/s]


In [100]:
soln_mat = mmul(temp, [[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
soln = soln_mat[0][0]

In [101]:
len(str(soln_mat[0][0]))

100002

In [104]:
hashlib.md5(str(soln%(10**10000)).encode()).hexdigest()

'328a2b646734252f998d4ceade7d2786'

In [31]:
mmul([[1,2,3,4]], temp)

IndexError: list index out of range

In [254]:
int(LA.matrix_power(a, 25)[0,0])

-45998219304081287323593671180288

In [231]:
LA.matrix_power(a, 25) # 1 2 3 0

array([[-4.59982193e+31,  1.27008177e+31, -1.14933110e+30,
         3.41973610e+28],
       [ 1.90451943e+33, -3.72548819e+32,  2.29942233e+31,
        -4.31186520e+29],
       [-2.40136397e+34,  6.02191951e+33, -5.02335962e+32,
         1.39393064e+31],
       [ 7.76307852e+35, -1.57120077e+35,  1.02176507e+34,
        -2.09610528e+32]])

In [159]:
a = np.matmul(np.matmul(eigenvectors.real, eigenvalues.real), LA.inv(eigenvectors.real))
temp = a
# 
# temp = LA.matrix_power(temp, 4)
for i in range(8):
    temp = LA.matrix_power(temp, 2)
    temp = np.divide(temp, 10)
temp = np.divide(temp, 10**80)

temp = LA.matrix_power(temp, 5**2)
temp = np.divide(temp, 10**80)
temp = LA.matrix_power(temp, 5**2)
temp = np.divide(temp, 10**120)
temp = LA.matrix_power(temp, 5)
temp = np.divide(temp, 10**275)
temp = LA.matrix_power(temp, 5)
temp = np.divide(temp, 10**70)
temp = LA.matrix_power(temp, 5)
# 3+2**n+5**m
np.matmul(temp, np.array((1,2,3,4))).tolist()[3]

-2.7474188648513183e+288

In [162]:
a = int(-2.7474188648513183e+288) % (10**10000)

In [164]:

hashlib.md5(str(a).encode()).hexdigest()

'5de551a5d43c65d2c52336bb6ee58f63'

In [21]:

for i in range(2000): # n-4
    temp = np.matmul(temp, a, dtype=object)
    if int(temp[0][0]) << 10000 > 1:
        temp = np.mod(temp, 2**10000)
    

OverflowError: (34, 'Result too large')

In [8]:
np.ones((4,4)), np.zeros((4,4))

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [6]:
for j in range(a.shape[0]):
    for k in range(a.shape[1]):
        temp[i][j] = 

array([[-6.13441159e-14,  1.00000000e+00,  1.35775706e-16,
        -1.68069501e-17],
       [-1.94126990e-12, -1.69996192e-14,  1.00000000e+00,
        -3.59603493e-16],
       [-1.64752292e-11,  2.02193258e-12,  7.39144724e-14,
         1.00000000e+00],
       [ 5.56920000e+04, -9.54900000e+03,  3.01000000e+02,
         2.10000000e+01]])

In [168]:
np.matmul(temp, np.array((1,2,3,4))).round().astype(np.int64)
# 5 6 7 8 

array([-2.20631148e+264,  4.63325412e+265, -9.72983364e+266,
        2.04326506e+268])

In [125]:
eigenvectors.real, eigenvalues.real, LA.inv(eigenvectors).real

(array([[-1.95368676e-05, -2.27831796e-04, -2.27831796e-04,
         -3.82010009e-03],
        [-7.25299567e-04,  3.38147971e-03,  3.38147971e-03,
          2.43357045e-02],
        [-2.69264998e-02,  2.06670015e-02,  2.06670015e-02,
         -1.55029057e-01],
        [-9.99637153e-01, -9.97874453e-01, -9.97874453e-01,
          9.87602740e-01]]),
 array([[37.12466004,  0.        ,  0.        ,  0.        ],
        [ 0.        , -4.87711184,  0.        ,  0.        ],
        [ 0.        ,  0.        , -4.87711184,  0.        ],
        [ 0.        ,  0.        ,  0.        , -6.37043636]]),
 array([[-8.93473962e+02, -1.77262702e+02, -9.60377858e+00,
         -5.95595725e-01],
        [ 3.25818425e+02,  8.70248839e+01,  4.42932673e+00,
         -1.88819360e-01],
        [ 3.25818425e+02,  8.70248839e+01,  4.42932673e+00,
         -1.88819360e-01],
        [-2.45947071e+02, -3.56273367e+00, -7.70015989e-01,
          2.81331280e-02]]))

In [119]:
eigenvectors.real.round().astype(np.int32), eigenvalues.real.round().astype(np.int32), LA.inv(eigenvectors).real.round().astype(np.int32)

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [-1, -1, -1,  1]], dtype=int32)

In [88]:
a = np.array([[0,1],[1,1]])
eigenvectors = LA.eig(a).eigenvectors
eigenvalues = np.diag(LA.eig(a).eigenvalues)
np.matmul(np.matmul(eigenvectors, eigenvalues), LA.inv(eigenvectors)).astype(np.int32)

array([[0, 1],
       [1, 1]], dtype=int32)

In [ ]:
def m_func(i):
    if i == 0: return 1
    if i == 1: return 2
    if i == 2: return 3
    if i == 3: return 4

    return 55692*m_func(i-4) - 9549*m_func(i-3) + 301*m_func(i-2) + 21*m_func(i-1)

In [213]:
import functools
ITERS = 16

@functools.cache
def m_func(i):
    if i == 0: return 1
    if i == 1: return 2
    if i == 2: return 3
    if i == 3: return 4

    return 55692*m_func(i-4) - 9549*m_func(i-3) + 301*m_func(i-2) + 21*m_func(i-1)



sol = m_func(ITERS)
sol

203436411134911968921

In [186]:
from tqdm import tqdm
a = np.matmul(np.matmul(eigenvectors.real, eigenvalues.real), LA.inv(eigenvectors.real)).astype(object).tolist()
temp = a
for i in range(4):
    temp = mmul(temp, temp)
# for i in tqdm(range(2)): # 
#     temp = mmul(mmul(mmul(mmul(temp, temp), temp), temp), temp)
soln_mat = mmul(temp, [[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
soln = soln_mat[0][0]
soln_mat[0][0]

2.0343641113490948e+20

In [189]:
np.matmul(np.matmul(eigenvectors.real, eigenvalues.real), LA.inv(eigenvectors.real))

array([[-6.13441159e-14,  1.00000000e+00,  1.35775706e-16,
        -1.68069501e-17],
       [-1.94126990e-12, -1.69996192e-14,  1.00000000e+00,
        -3.59603493e-16],
       [-1.64752292e-11,  2.02193258e-12,  7.39144724e-14,
         1.00000000e+00],
       [ 5.56920000e+04, -9.54900000e+03,  3.01000000e+02,
         2.10000000e+01]])

In [266]:
a = np.matmul(np.matmul((eigenvectors), eigenvalues, dtype=np.float64), LA.inv((eigenvectors)), dtype=np.float64)
int(np.matmul(LA.matrix_power(a, 16), [[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])[0][0])
# LA.matrix_power(a, 16)

1158485388669261185024

In [ ]:
1158485388669261185024
203436411134911968921